### ISSUE TITLE
Interactic Incompatability

### ISSUE THREAD

**Issue by Noaaan** [Tigereye504/lava-java#5]
Related to https://github.com/gliscowo/interactic/issues/13

Your method that renders the tooltip for your Lava Java has the worled marked with a `@Nullable` annotation, yet it is never checked whether or not it is null. When Interactic renders the tooltip on the item, the world is null, and as such it can crash whenever it is invoked.

Happens here: https://github.com/Tigereye504/lava-java/blob/master/src/main/java/net/tigereye/lavajava/item/LavaJavaItem.java#L110

**Comment by Tigereye504** [comment]
Fixed in 0.4.2
